books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    # Book View and Search Result
    path('', views.BookViews.as_view(), name='books'),
    path('result/', views.search_view, name='search-result'),
    # Author Management
    path('add_author/', views.AddAuthorView.as_view(), name='add_author'),
    path('edit_author/<id>/',
         views.update_author_view, name='edit_author'),
    path('delete_author/<id>/',
         views.delete_author, name='delete_author'),
    # Book Management
    path('edit/<slug:slug>/',
         views.update_book_view, name='edit_book'),
    path('delete/<slug:slug>/',
         views.delete_book, name='delete_book'),
    path('add_book/', views.AddBookView.as_view(), name='add_book'),
    # Book Details at the bottom due to slug
    path('<slug:slug>/', views.BookDetailView.as_view(), name='book-details'),
]

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.order_view, name='shopping_cart'),
    path('add/<slug:slug>', views.order_item, name='in_cart'),
    path('remove/<slug:slug>/', views.remove_book, name='remove_book'),
    path('adjust/<slug:slug>', views.adjust_cart, name='adjust_cart'),
]

gosip/urls.py
from .views import handler404
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls')),
    path('books/', include('books.urls', namespace='books')),
    path('cart/', include('cart.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('profiles/', include('profiles.urls')),
    path('checkout/', include('checkout.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'gosip.views.handler404'

wishlist/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.wishlist_view, name='wishlist'),
    path('like/<slug:slug>/', views.like_book, name='wish'),
    path('remove/<slug:slug>/', views.remove_book, name='remove_book'),
]

wishlist/models.py
from django.db import models

# Create your models here.

wishlist/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.http import HttpResponseRedirect


def wishlist_view(request):
    """ function renders wishlist view """
    return render(request, 'wishlist/wish.html')


def like_book(request, slug):
    """ Add wish item to wishlist"""

    # check if likes dict exist else create
    wishlist = request.session.get('wishlist', {})
    # redirects to the current page
    redirect_url = request.POST.get('redirect_url')

    if slug not in list(wishlist.keys()):
        wishlist[slug] = slug
    elif slug in list(wishlist.keys()):
        wishlist.pop(slug)
    request.session['wishlist'] = wishlist
    return redirect(redirect_url)


def remove_book(request, slug):
    """ Returning a liked item from the wishlist """
    try:
        wishlist = request.session.get('wishlist', {})
        wishlist.pop(slug)

        request.session['wishlist'] = wishlist
        return HttpResponse(status=200)

    except Exception as error:
        return HttpResponse(status=500)

wishlist/templates/wishlist/wish.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container page">
    <h2 class="text-center text-uppercase">Wishlist</h2>
    <div class="row justify-content-between my-5">
        <div class="col-10 mx-auto checkout-items">
            {% if books_liked %}
            {% for item in books_liked %}
            <div class="container my-2">
                <div class="row">
                    <div class="col-12 col-md-3">
                        <div class="book-wishlist-card py-3 px-3">
                            {% if item.book.image %}
                            <a href="{% url 'books:book-details' slug=item.book.slug %}">
                                <img src="{{ item.book.image.url }}" alt="book image" width="98" height="150">
                            </a>
                            {% else %}
                                <a href="{% url 'books:book-details' slug=item.book.slug %}">
                                    <img class="img-fluid" src="{{ MEDIA_URL }}no-image-man.jpg" width="98" height="150" alt="no image available">
                                </a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-12 col-md-6 book-information">
                        <div class="d-grid gap-2 mt-3 mb-2">
                            <p><strong>{{ item.book.title }}</strong></p>
                            <a class="text-decoration-none" href="{% url 'books:book-details' slug=item.book.slug %}#about-author">
                                <small class="author-link">{{ item.book.author }}</small>
                            </a>
                            {% if item.book.genre %}
                            <a class="text-decoration-none" href="#">
                                <small class="mute genre-link"><i class="fa-solid fa-tag"></i> {{ item.book.genre }}</small>
                            </a>
                            {% endif %}
                            <p>Price : {{ item.book.price }} €</p>
                        </div>
                    </div>
                    <div class="col-12 col-md-3">
                        <div class="d-flex gap-2 wish-action">
                            <button class="remove-book btn" id="remove_{{ item.book.slug }}"><i class="fa-solid fa-trash"></i></button>
                            <!--Add liked book to cart-->
                            <form action="{% url 'in_cart' slug=item.book.slug %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="quantity" value="1" id="id_qty_{{ item.book.id }}">
                                <button class="btn btn-cart" type="submit">Add to Cart</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <hr class="wishlist-hr">
            {% endfor %}
            {% else %}
            <div class="d-grid my-auto">
                <p class="fs-2 text-center">Your Wishlist is empty.</p>
                <div class="d-flex justify-content-center mt-4">
                    <a class="btn btn-bookstore" href="{% url 'books:books' %}"><i class="fa-solid fa-arrow-left"></i> Back to Bookstore</a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}
{% block postloadjs %}
    {{block.super}}
    <script>

        // Remove like on click and reload page
      $('.remove-book').click(function(e) {
          var csrfToken = "{{ csrf_token }}";
          var bookId = $(this).attr('id').split('remove_')[1];
          var url = `/wishlist/remove/${bookId}/`;
          var data = {'csrfmiddlewaretoken': csrfToken};

          $.post(url, data)
          .done(() => {
              location.reload();
          });
      })

        // Remove like on click and reload page
      $('.add-book').click(function(e) {
          var csrfToken = "{{ csrf_token }}";
          var bookId = $(this).attr('id').split('id_qty_')[1];
          var url = `/cart/add/${bookId}/`;
          var data = {'csrfmiddlewaretoken': csrfToken};

          $.post(url, data)
          .done(() => {
              location.reload();
          });
      })
    </script>
{% endblock %}