books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    # Book View and Search Result
    path('', views.BookViews.as_view(), name='books'),
    path('result/', views.search_view, name='search-result'),
    # Author Management
    path('add_author/', views.AddAuthorView.as_view(), name='add_author'),
    path('edit_author/<id>/',
         views.update_author_view, name='edit_author'),
    path('delete_author/<id>/',
         views.delete_author, name='delete_author'),
    # Book Management
    path('edit/<slug:slug>/',
         views.update_book_view, name='edit_book'),
    path('delete/<slug:slug>/',
         views.delete_book, name='delete_book'),
    path('add_book/', views.AddBookView.as_view(), name='add_book'),
    # Book Details at the bottom due to slug
    path('<slug:slug>/', views.BookDetailView.as_view(), name='book-details'),
]

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.order_view, name='shopping_cart'),
    path('add/<slug:slug>', views.order_item, name='in_cart'),
    path('remove/<slug:slug>/', views.remove_book, name='remove_book'),
    path('adjust/<slug:slug>', views.adjust_cart, name='adjust_cart'),
]

gosip/urls.py
from .views import handler404
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls')),
    path('books/', include('books.urls', namespace='books')),
    path('cart/', include('cart.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('profiles/', include('profiles.urls')),
    path('checkout/', include('checkout.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'gosip.views.handler404'

templates/includes/footer.html
<footer>
  <hr class="border border-danger">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12 d-flex justify-content-center">
        <!-- Begin Mailchimp Signup Form -->
        <div id="mc_embed_signup">
            <form action="https://gmail.us13.list-manage.com/subscribe/post?u=288d4884336ddad0922fbb533&amp;id=f83c6c95b9&amp;f_id=006a61e2f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                <div id="mc_embed_signup_scroll">
                <h2>Subscribe to our Newsletter</h2>
                <p>Be the first to get informed about our special offers</p>
                <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
                  <div class="mc-field-group">
                    <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
                  </label>
                    <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" required>
                    <span id="mce-EMAIL-HELPERTEXT" class="helper_text"></span>
                  </div>
                    <div id="mce-responses" class="clear foot">
                      <div class="response" id="mce-error-response" style="display:none"></div>
                      <div class="response" id="mce-success-response" style="display:none"></div>
                    </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                      <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_288d4884336ddad0922fbb533_f83c6c95b9" tabindex="-1" value=""></div>
                    <div class="optionalParent">
                      <div class="clear foot">
                          <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
                        <p class="brandingLogo"><a href="http://eepurl.com/ihCFnr" title="Mailchimp - email marketing made easy and fun"><img src="https://eep.io/mc-cdn-images/template_images/branding_logo_text_dark_dtp.svg" alt="Mailchimp"></a></p>
                    </div>
                </div>
            </div>
        </form>
        </div>
        <!--End mc_embed_signup-->
      </div>
    </div>
  </div>
  <div class="container-fluid footer-links py-2">
        <div class="row">
          <div class="col-6 col-md-3">
            <!--company-networks-->
            <div class="social-networks ms-5">
              <strong>Company</strong>
              <ul class="list-unstyled">
                <li>
                  <a href="{% url 'about' %}" class="nav-link"><small>About</small></a>
                </li>
                <li>
                  <a href="{% url 'contact' %}" class="nav-link"><small>Contact</small></a>
                </li>
                <li>
                  <a href="{% url 'team' %}" class="nav-link"><small>Team</small></a>
                </li>
                <li>
                  <a
                    href="https://folarin-ogungbemi.github.io/Portfolio-Project-1/"
                    class="nav-link"
                    target="_blank"
                    rel="noopener"
                    aria-label="visit our Blog page(open in a new tab)"
                    ><small>Blog</small></a
                  >
                </li>
                <li>
                  <a
                    href="https://folarin-ogungbemi.github.io/twain-land/"
                    class="nav-link"
                    target="_blank"
                    rel="noopener"
                    aria-label="visit our Game website page(open in a new tab)"
                    ><small>Games</small></a>
                </li>
              </ul>
            </div>
            <!--/.company-networks-->
          </div>
          <div class="col-6 col-md-3">
            <!--Sponsor-networks-->
            <div class="social-networks ms-5">
              <strong>Sponsors</strong>
              <ul class="list-unstyled">
                <li>
                  <a
                    href="https://codeinstitute.net/"
                    class="nav-link"
                    target="_blank"
                    rel="noopener"
                    aria-label="visit our Code Institute page(open in a new tab)"
                   ><small>Code Institute</small></a>
                </li>
                <li>
                  <a
                  href="https://www.python.org/"
                  class="nav-link"
                  target="_blank"
                  rel="noopener"
                  aria-label="visit our Python page(open in a new tab)"
                  ><small>Python</small></a>
                </li>
                <li>
                  <a
                  href="https://www.djangoproject.com/"
                  class="nav-link"
                  target="_blank"
                  rel="noopener"
                  aria-label="visit our Django page(open in a new tab)"
                  ><small>Django</small></a>
                </li>
                <li>
                  <a
                  href="https://www.javascript.com/"
                  class="nav-link"
                  target="_blank"
                  rel="noopener"
                  aria-label="visit our Javascript page(open in a new tab)"
                  ><small>Javascript</small></a>
                </li>
                <li>
                  <a
                  href="https://stripe.com/en-de"
                  class="nav-link"
                  target="_blank"
                  rel="noopener"
                  aria-label="visit our Stripe page(open in a new tab)"
                  ><small>Stripe</small></a>
                </li>
              </ul>
            </div>
            <!--/.Sponsor-networks-->
          </div>
          <!--company-col./-->
          <div class="col-6 col-md-3">
            <!--Product-networks-->
            <div class="social-networks ms-5">
              <strong>Categories</strong>
              <ul class="list-unstyled">
                <li><a class="nav-link" href="{% url 'books:search-result' %}?genre=Education"><small>Education</small></a></li>
                <li><a class="nav-link" href="{% url 'books:search-result' %}?genre=Fantasy"><small>Fantasy</small></a></li>
                <li><a class="nav-link" href="{% url 'books:search-result' %}?genre=History"><small>History</small></a></li>
                <li><a class="nav-link" href="{% url 'books:search-result' %}?genre=Kids"><small>Kids</small></a></li>
                <li><a class="nav-link" href="{% url 'books:search-result' %}?genre=Sports"><small>Sports</small></a></li>
              </ul>
            </div>
            <!--/.Product-networks-->
          </div>
          <!--Product-col./-->
          <div class="col-6 col-md-3">
            <!--social-networks-->
            <div class="social-networks ms-5">
              <strong>Socials</strong>
              <ul class="list-unstyled">
                <li>
                  <a
                    href="https://www.facebook.com/profile.php?id=100089052437606"
                    target="_blank"
                    rel="noopener"
                    class="nav-link"
                    aria-label="visit our Facebook page(open in a new tab)"
                    ><small>Facebook</small></a>
                </li>
              </ul>
            </div>
            <!--/.social-networks-->
          </div>
          <!--follow-links-col./-->
        </div>
        <!--footer-links-row./-->
        <div class="d-flex justify-content-center">
          <a href="https://www.privacypolicygenerator.info/live.php?token=FIog0DcKZQldufrS5DK0VieBrJQiAevw" class="text-decoration-none text-info ms-2">Privary Policy</a>
        </div>
    </div>
    <!--footer-links-container./-->
    <!--Copywrite-->
    <div class="footer-copywrite">
        <div class="row">
          <div class="col-12 d-flex justify-content-center">
            <span>
              <a
                href="https://github.com/folarin-ogungbemi"
                target="_blank"
                rel="noopener"
                aria-label="visit folarin's github page(open in a new tab)"
                class="nav-link d-inline"
                ><small>&copy; 2022 Folarin projects.</small>
                <i class="fa-brands fa-github"></i></a
            ></span>
          </div>
      </div>
  </div>
  <!--Copywrite-->
</footer>

templates/includes/main-nav.html
<!--All Books-->
<li class="nav-item dropdown">
  <a
    class="nav-link ps-4 dropdown-toggle"
    role="button"
    data-bs-toggle="dropdown"
    aria-expanded="false"
    href="#"
    >All Books</a
  >
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="{% url 'books:search-result' %}?sort=price&direction=asc">By Price</a></li>
    <li><a class="dropdown-item" href="{% url 'books:search-result' %}?sort=rating&direction=desc">By Rating</a></li>
    <li><a class="dropdown-item" href="{% url 'books:search-result' %}?sort=genre&direction=asc">By Genre</a></li>
    <li><a class="dropdown-item" href="{% url 'books:books' %}">All Books</a></li>
  </ul>
</li>
  <!--/.All Products-->
 <!--Genres-->
<li class="nav-item dropdown">
  <a
    class="nav-link ps-4 dropdown-toggle"
    role="button"
    data-bs-toggle="dropdown"
    aria-expanded="false"
    href="#"
    >Genres</a
  >
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="{% url 'books:search-result' %}?genre=Education">Education</a></li>
    <li><a class="dropdown-item" href="{% url 'books:search-result' %}?genre=Fantasy">Fantasy</a></li>
    <li><a class="dropdown-item" href="{% url 'books:search-result' %}?genre=History">History</a></li>
    <li><a class="dropdown-item" href="{% url 'books:search-result' %}?genre=Kids">Kids</a></li>
    <li><a class="dropdown-item" href="{% url 'books:search-result' %}?genre=Sports">Sports</a></li>
  </ul>
</li>
<!--/.Genres-->
  <!--Special-Offers-->
  <li class="nav-item dropdown">
    <a
      class="nav-link ps-4 dropdown-toggle"
      role="button"
      data-bs-toggle="dropdown"
      aria-expanded="false"
      href="#"
      >Specials</a
    >
    <ul class="dropdown-menu">
      <li><a class="dropdown-item" href="{% url 'books:search-result' %}?special=Bestseller">Bestseller</a></li>
      <li><a class="dropdown-item" href="{% url 'books:search-result' %}?special=New%20Arrivals">New Arrivals</a></li>
      <li><a class="dropdown-item" href="{% url 'books:search-result' %}?special=SALE">SALE</a></li>
      <li><a class="dropdown-item" href="{% url 'books:search-result' %}?special=Recommendations">Recommendations</a></li>
      <li><a class="dropdown-item" href="{% url 'books:search-result' %}?special=Special">All Specials</a></li>
    </ul>
  </li>
  <!--/.Special-Offers-->
  

templates/includes/mobile-bottom-nav.html
<div class="navbar navbar-expand d-flex d-md-none fixed-bottom mobile-bottom-link">
    <ul class="navbar-nav flex-grow-1 justify-content-around">
      <li class="nav-item">
        <a class="nav-link ps-4" href="{% url 'home' %}"><i class="fa-solid fa-house"></i></a>
      </li>
      <li class="nav-item">
        {% if user.is_authenticated %}
        <a class="nav-link ps-4" href="{% url 'user_profile'%}"><i class="fa-solid fa-user"></i></a>
        {% else %}
        <a class="nav-link ps-4" href="{% url 'account_login' %}"><i class="fa-solid fa-user"></i></a>
        {% endif %}
      </li>
      <li class="nav-item mobile-wish-box">
        <small class="text-danger"><strong class="mobile-wish-items">{{ like_count }}</strong></small>
        <a class="nav-link ps-4" href="{% url 'wishlist' %}"><i class="fa-regular fa-heart"></i></a>
      </li>
      <li class="nav-item mobile-cart-box">
        <small class="text-danger"><strong class="mobile-cart-items">{{book_count}}</strong></small>
        <a class="nav-link ps-4" href="{% url 'shopping_cart'%}"><i class="fa-solid fa-basket-shopping"></i></a>
      </li>
    </ul>
</div>

templates/includes/offcanvas-nav.html
<!--offcanvas-navigation.-->
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasDarkNavbar">
  <div class="offcanvas-header">
    <a class="navbar-brand ps-4" href="{% url 'home' %}"><h3 class="logo"><strong>G<span class="brand-color">o</span></strong>sip Bookstore</h3></a>
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
      <li class="nav-item">
        <a class="nav-link ps-4 trans-link" href="{% url 'home' %}"><i class="fa-solid fa-house me-2"></i>Home</a>
      </li>
      <!--main-nav-->
      {% include 'includes/main-nav.html'%}
      <!--main-nav ./-->
      <li class="nav-item">
          <a class="nav-link ps-4 trans-link" href="{% url 'about' %}"><i class="fa-solid fa-heart-pulse me-2"></i>About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link ps-4 trans-link" href="{% url 'contact' %}"><i class="fa-solid fa-link me-2"></i>Contact</a>
        </li>
        {% if user.is_authenticated %}
          {% if request.user.is_superuser%}
          <li class="nav-item">
          <a href="{% url 'books:add_author' %}" class="nav-link ps-4 trans-link"><i class="fa-solid fa-list-check me-2"></i>Admin Management</a>
        </li>
          {% endif %}
        {% endif %}
    </ul>
    <div class="d-grid mt-4">
      {% if user.is_authenticated %}
      <a class="btn btn1 rounded-pill" href="{% url 'account_logout' %}">Logout</a>
      {% else %}
      <a class="btn btn1 rounded-pill" href="{% url 'account_login' %}">Login</a>
      <a class="btn btn2 rounded-pill mt-2" href="{% url 'account_signup' %}">Register</a>
      {% endif %}
    </div>
  </div>
</div>

templates/includes/search-modal.html
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="searchModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
            <form method="GET" action="{% url 'books:search-result' %}"
            class="d-flex form-control gosip-search-box ms-5 me-5"
            role="search"
            id="searchModalLabel"
          >
            <input
              class="gosip-search form-control"
              type="search"
              name="q"
              placeholder="Search"
              aria-label="Search">
            <button class="search-btn me-2" type="submit">
              <i class="fa-solid fa-magnifying-glass"></i>
            </button>
          </form>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
      </div>
    </div>
</div>

templates/includes/top-nav.html
{% include 'includes/search-modal.html' %}
<div class="navbar navbar-expand top-nav d-none d-md-flex">
  <div class="d-flex form-control gosip-search-box d-md-none d-xl-flex ms-5 me-5">
    <div class="gosip-search form-control" data-bs-toggle="modal" data-bs-target="#searchModal">Search</div>
    <div class="search-btn me-2">
      <i class="fa-solid fa-magnifying-glass"></i>
    </div>
  </div>
  <ul class="d-flex list-unstyled gap-5 ms-5 py-1 my-auto">
    <li class="nav-item mt-1 d-inline dropdown">
      {% if user.is_authenticated %}
      <small class="user">Hi, <span>{{user.username}}</span></small>
      {% else %}
      <i class="fa-solid fa-user d-flex justify-content-center"></i>
      {% endif %}
      <a
      class="nav-link dropdown-toggle nav-hover me-2"
      href="#"
      role="button"
      data-bs-toggle="dropdown"
      aria-expanded="false"
      >Account
      </a>
      <ul class="dropdown-menu">
        {% if user.is_authenticated %}
        {% if request.user.is_superuser%}
        <li>
          <a href="{% url 'books:add_author' %}" class="dropdown-item">Admin Management</a>
        </li>
        {% endif %}
        <li><a class="dropdown-item" href="{% url 'user_profile' %}">My Profile</a></li>
        <li>
          <a class="dropdown-item" href="{% url 'account_logout' %}"
            >Logout</a
          >
        </li>
        {% else %}
        <li>
          <a class="dropdown-item" href="{% url 'account_signup' %}"
            >Register</a
          >
        </li>
        <li>
          <a class="dropdown-item" href="{% url 'account_login' %}"
            >Login</a
          >
        </li>
        {% endif %}
      </ul>
    </li>
    <li class="nav-item wish-box text-center">
      <small class="text-danger"><strong class="wish-items">{{ like_count }}</strong></small>
      <a class="nav-link d-grid gap-2 me-2" href="{% url 'wishlist' %}">
        <i class="fa-regular fa-heart"></i>
        <small class="nav-hover">Wishlist</small>
      </a>
    </li>
    <li class="nav-item cart-box text-center pe-4">
      <small class="text-danger"><strong class="cart-items">{{book_count}}</strong></small>
      <a class="nav-link d-grid gap-2" href="{% url 'shopping_cart'%}">
        <i class="fa-solid fa-basket-shopping"></i>
        <small class="nav-hover">Cart</small>
      </a>
    </li>
  </ul>
</div>