books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    # Book View and Search Result
    path('', views.BookViews.as_view(), name='books'),
    path('result/', views.search_view, name='search-result'),
    # Author Management
    path('add_author/', views.AddAuthorView.as_view(), name='add_author'),
    path('edit_author/<id>/',
         views.update_author_view, name='edit_author'),
    path('delete_author/<id>/',
         views.delete_author, name='delete_author'),
    # Book Management
    path('edit/<slug:slug>/',
         views.update_book_view, name='edit_book'),
    path('delete/<slug:slug>/',
         views.delete_book, name='delete_book'),
    path('add_book/', views.AddBookView.as_view(), name='add_book'),
    # Book Details at the bottom due to slug
    path('<slug:slug>/', views.BookDetailView.as_view(), name='book-details'),
]

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.order_view, name='shopping_cart'),
    path('add/<slug:slug>', views.order_item, name='in_cart'),
    path('remove/<slug:slug>/', views.remove_book, name='remove_book'),
    path('adjust/<slug:slug>', views.adjust_cart, name='adjust_cart'),
]

gosip/urls.py
from .views import handler404
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls')),
    path('books/', include('books.urls', namespace='books')),
    path('cart/', include('cart.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('profiles/', include('profiles.urls')),
    path('checkout/', include('checkout.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'gosip.views.handler404'

books/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.utils.text import slugify


class Author(models.Model):
    name = models.CharField(
        max_length=100,
        null=False,
        blank=False)
    book_title = models.CharField(
        max_length=100,
        null=False,
        blank=False)
    about = models.TextField()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Special(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


RATING = [
    (1, 'very bad'),
    (2, 'bad'),
    (3, 'okay'),
    (4, 'good'),
    (5, 'excellent'),
]


class Books(models.Model):
    title = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=260, unique=True)
    author = models.ForeignKey(
        Author,
        on_delete=models.CASCADE,
        related_name='book')
    genre = models.ForeignKey(
        Genre,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='book_category')
    special = models.ManyToManyField(
        Special,
        blank=True)
    publication_year = models.IntegerField()
    pages = models.IntegerField()
    language = models.CharField(max_length=100)
    isbn = models.IntegerField(unique=True)
    dimension = models.CharField(max_length=100)
    price = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        validators=[MinValueValidator(0)])
    rating = models.PositiveIntegerField(
        choices=RATING,
        null=True,
        blank=True)
    description = models.TextField(
        null=False,
        blank=False
    )
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Books, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Books'
        ordering = ['-created_on']

    def __str__(self):
        return f"{self.title} by {self.author}"

books/forms.py
from django import forms
from books.widgets import CustomClearableFileInput
from books.models import Books, Author


class AuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = '__all__'


class BookForm(forms.ModelForm):

    image = forms.ImageField(
            label="Image", required=False, widget=CustomClearableFileInput)

    class Meta:
        model = Books
        fields = [
            'title', 'author', 'genre', 'special',
            'publication_year', 'pages', 'language', 'isbn', 'dimension',
            'price', 'rating', 'description', 'image_url', 'image'
            ]

books/views.py
from django.shortcuts import render, reverse, redirect
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404

from books.models import Books, Genre, Special, Author

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Access security
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.db.models import Q
from django.db.models.functions import Lower
from django.contrib import messages
from .forms import BookForm, AuthorForm


class BookViews(ListView):
    model = Books
    template_name = "books/books.html"
    context_object_name = "books"
    paginate_by = 8


def search_view(request):
    """
    View that searches the Books queryset based on user input
    """

    query_set = Books.objects.all()
    query_sort = request.GET.get('sort', None)
    query_direction = request.GET.get('direction', None)
    query_specials = request.GET.get('special', None)
    query_genre = request.GET.get('genre', None)
    query_dict = request.GET.get('q', None)

    if request.GET:
        if query_sort:
            if query_sort == 'title':
                query_sort = 'lower_title'
                query_set = query_set.annotate(lower_title=Lower('title'))
            if query_direction:
                if query_direction == 'desc':
                    query_sort = f'-{query_sort}'
            query_set = query_set.order_by(query_sort)
        if query_specials:
            specials = query_specials.split(',')
            query_set = query_set.filter(special__name__in=specials)
            query_specials = Special.objects.filter(name__in=specials)

        if query_genre:
            genres = query_genre.split(',')
            query_set = query_set.filter(genre__name__in=genres)
            query_genre = Genre.objects.filter(name__in=genres)

        if query_dict:
            queries = Q(title__icontains=query_dict) | Q(
                description__icontains=query_dict)
            query_set = query_set.filter(queries)

    sorting = f'{query_sort}_{query_direction}'

    context = {
            'books': query_set,
            'search_term': query_dict,
            'genre': query_genre,
            'special': query_specials,
            'sorting': sorting,
    }
    return render(request, "books/books.html", context)


class BookDetailView(DetailView):
    model = Books
    template_name = 'books/book-details.html'
    context_object_name = 'book'


@method_decorator(login_required, name='dispatch')
class AddAuthorView(CreateView):
    model = Author
    form_class = AuthorForm
    template_name = 'books/add_author.html'
    success_url = reverse_lazy('books:add_author')
    context_object_name = 'form'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            messages.error(self.request, "Permission denied!")
            return redirect(reverse('home'))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "Author successfully added.")
        return redirect(reverse('books:add_book'))

    def form_invalid(self, form):
        messages.error(
            self.request,
            "Failed to add author!. Please check the validity of the form.")
        return super().form_invalid(form)


@login_required
def update_author_view(request, id):
    """
    Function provides ability to edit and(or)
    update form and redirects to book-details
    """
    if not request.user.is_superuser:
        messages.error(request, "sorry, Only Adminitrators allowed")
        return redirect(reverse('home'))

    author = get_object_or_404(Author, pk=id)
    if request.method == 'POST':
        form = AuthorForm(request.POST, instance=author)
        if form.is_valid():
            form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                'Author has been successfully updated.')
            return redirect(reverse('books:books'))
    form = AuthorForm(instance=author)
    context = {
        'form': form,
        'author': author,
    }
    return render(request, 'books/edit_author.html', context)


@login_required
def delete_author(request, id):
    """
    Function creates ability to delete and redirects
    """
    if not request.user.is_superuser:
        messages.error(request, "sorry, Only Adminitrators allowed")
        return redirect(reverse('home'))

    author = get_object_or_404(Author, pk=id)
    author.delete()
    messages.add_message(
        request,
        messages.SUCCESS,
        f'Author "{author.name}" has been successfully deleted.')
    return redirect('books:books')


@method_decorator(login_required, name='dispatch')
class AddBookView(CreateView):
    model = Books
    form_class = BookForm
    template_name = 'books/add_book.html'
    success_url = 'books/add_book'
    context_object_name = 'form'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            messages.error(self.request, 'Permission denied!')
            return redirect(reverse('home'))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Book successfully added.')
        return redirect(reverse('books:books'))

    def form_invalid(self, form):
        messages.error(
            self.request,
            "Failed to add book!. Please check the validity of the form.")
        return super().form_invalid(form)


@login_required
def update_book_view(request, slug):
    """
    Function provides ability to edit and(or)
    update form and redirects to book-details
    """
    if not request.user.is_superuser:
        messages.error(request, "Sorry, only administrators are allowed.")
        return redirect(reverse('home'))

    book = get_object_or_404(Books, slug=slug)

    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            messages.success(request, 'Book has been successfully updated.')
            return redirect(reverse('books:book-details', args=[book.slug]))
    else:
        form = BookForm(instance=book)

    context = {
        'form': form,
        'book': book,
    }

    return render(request, 'books/edit_book.html', context)


@login_required
def delete_book(request, slug):
    """
    Function creates ability to delete and redirects
    """
    if not request.user.is_superuser:
        messages.error(request, "sorry, Only Adminitrators allowed")
        return redirect(reverse('home'))

    book = get_object_or_404(Books, slug=slug)
    book.delete()
    messages.add_message(
        request,
        messages.SUCCESS,
        'Book has been successfully deleted.')
    return redirect('books:books')

books/templates/books/add_author.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container page">
    <h2 class="text-center text-uppercase">Author Management</h2>
    <h5 class=" text-center mute">Add Author</h5>
    <div class="row row-cols-2 my-5">
        <div class="col-12 form mx-auto">
            <form method="POST" action="{% url 'books:add_author' %}"class="text-center my-3" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="d-flex justify-content-center gap-2">
                    <a class="btn btn-secondary" href="{% url 'books:books' %}">Cancel</a>
                    <input type="submit" value="Add Author" class="btn btn-primary">
                    <a class="btn btn-danger" href="{% url 'books:add_book' %}"> Go To Book Management</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

books/templates/books/add_book.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container page">
    <h2 class="text-center text-uppercase">Book Management</h2>
    <h5 class=" text-center mute">Add a Book</h5>
    <div class="row row-cols-2 my-5">
        <div class="col-12 form">
            <form method="POST" action="{% url 'books:add_book' %}"class="text-center my-3" enctype="multipart/form-data">
                {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                <div class="d-flex justify-content-center gap-2">
                    <a class="btn btn-secondary" href="{% url 'books:books' %}">Cancel</a>
                    <input type="submit" value="Add Book" class="btn btn-primary">
                    <a class="btn btn-danger" href="{% url 'books:add_author' %}"> Go To Author Management</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

books/templates/books/book-details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container page-margin">
    <div class="row row-cols-2">
        <!--Book Image-->
        <div class="col-12 col-sm-6 col-md-5 col-lg-4 book-img">
            <div class="container-sm book-card py-4 px-3">
                {% if book.image %}
                    <img src="{{ book.image.url }}" alt="book image" width="200" height="280">
                {% else %}
                    <a href="#"><img class="img-fluid" src="{{ MEDIA_URL }}no-image-man.jpg" 
                        width="200" height="280" alt="no image available">
                    </a>
                {% endif %}
                <form action="{% url 'wish' slug=book.slug %}" method="POST">
                    {% csrf_token %}
                    <button class="like-book btn ms-5 submit detail-book-like" id="like_{{ book.slug }}"><i class="fa-regular fa-heart"></i></button>
                    <input type="hidden" name="redirect_url" value="{{ request.path }}">
                </form>
            </div>
        </div>
        <!--Book details-->
        <div class="col-12 col-sm-6 col-md-7 col-lg-8 book-details">
            <div class="col-12 d-block d-sm-none my-4">
            </div>
            <div class="cotainer-sm">
                <h3>{{ book.title }}</h3>
                <a class="text-decoration-none" href="{% url 'books:book-details' slug=book.slug %}#about-author">
                    <small class="author-link">{{ book.author}} | {{ book.publication_year }}</small>
                </a>
                <p> 
                    <strong>{{ book.price }} €</strong>
                </p>
                {% if book.genre %}
                <div class="d-flex justify-content-start">
                  <a class="text-decoration-none" href="#">
                    <small class="mute genre-link"><i class="fa-solid fa-tag"></i> {{ book.genre }}</small>
                  </a>
                </div>
                {% endif %}
                {% if book.rating %}
                <small class="mute"><i class="fa-solid fa-star"></i> {{ book.rating }} / 5 </small>
                {% else %}
                <small> No Rating</small>
                {% endif %}
                <div class="summary my-3">
                    <h4>Description</h4>
                    {{ book.description | safe }}
                </div>
                <!--update or delete book as a superuser-->
                {% if request.user.is_superuser%}
                    <div class="d-flex justify-content-end">
                        <a href="{% url 'books:edit_book' slug=book.slug %}" class="text-primary text-decoration-none">edit</a><span class="text-muted">|</span>
                        <a class="text-danger text-decoration-none" href="{% url 'books:delete_book' slug=book.slug %}" role="button">delete</a>
                    </div>
                {% endif %}
                <!-- Add book to cart form-->
                <form action="{% url 'in_cart' slug=book.slug %}" method="POST">
                    {% csrf_token %}
                    <div class="d-grid my-4">
                        <label for="id_qty_{{ book.id }}" class="ms-5 fw-semibold">Quantity</label>
                        <div class="qty-group d-flex">
                            <div class="input-group-prepend">
                                <button class="decrement-qty btn"
                                data-book_id="{{ book.id }}" id="decrement-qty_{{ book.id }}">
                                 <span class="icon">
                                    <i class="fa-solid fa-minus"></i>
                                 </span>
                                </button>
                            </div>
                            <input type="number" class="form-control qty_select text-center"
                                name="quantity" value="1" min="1" max="50"
                                data-book_id="{{ book.id }}" id="id_qty_{{ book.id }}">
                                <div class="input-group-postpend">
                                    <button class="increment-qty btn"
                                    data-book_id="{{ book.id }}" id="increment-qty_{{ book.id }}">
                                     <span class="icon">
                                        <i class="fa-solid fa-plus"></i>
                                     </span>
                                    </button>
                                </div>
                        </div>
                    </div>
                    <div class="row shop gap-3 d-flex justify-content-center text-center">
                        <div class="col-12 col-lg-6">
                            <button class="btn" type="submit">Add to Cart</button>
                        </div>
                        <div class="col-12 col-lg-6">
                            <a href="{% url 'books:books' %}" class="text-decoration-none btn"><i class="fa-solid fa-arrow-left"></i> Bookstore</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<hr class="book-hr my-4">
<div class="container">
    <h4 class="mb-3">Book Information</h4>
    <div>
        <p><strong>Published :</strong> {{book.publication_year}}</p>
        <p><strong>Language :</strong> {{book.language}}</p>
        <p><strong>Pages :</strong> {{book.pages}} pages</p>
        <p><strong>ISBN :</strong> {{book.isbn}}</p>
        <p><strong>Dimension :</strong> {{book.dimension}}</p>
    </div>
</div>
<hr class="book-hr my-4">
<div class="container">
    <div class=" d-flex justify-content-start mb-3">
        <h4 id="about-author">About the Author</h4>
    </div>
    <h5>{{book.author}}</h5>
    {{book.author.about | safe}}
        <!--update or delete author as a superuser-->
    {% if request.user.is_superuser%}
    <div class="d-flex justify-content-end">
        <a href="{% url 'books:edit_author' book.author.id %}" class="text-primary text-decoration-none">edit</a><span class="text-muted">|</span>
        <a class="text-danger text-decoration-none" href="{% url 'books:delete_author' book.author.id %}" role="button">delete</a>
    </div>
    {% endif %}
</div>
{% endblock %}
{% block postloadjs %}
    {{block.super}}
    {% include 'books/includes/quantity_select_script.html' %}
{% endblock %}  

books/templates/books/books.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container page">
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
              <h2 class="text-uppercase">books</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-12 d-flex justify-content-end">
              <p class=" mute mt-3">
                  {% if search_term or genre or special or sorting is true %}
                  <span>
                    <a class="books-link" href="{% url 'books:books' %}">Books Home</a> |
                  </span>
                  {% endif %}
                  {% if books|length < 1 %}
                  <span>No Books found for <strong>"{{search_term}}"</strong></span>
                  {% elif books|length == 1 %}
                  {{ books|length }} Book{% if search_term %} found for <strong>"{{ search_term }}"</strong>{% endif %}
                  {% else %}
                  {{ books|length }} Books{% if search_term %} found for <strong>"{{ search_term }}"</strong>{% endif %}
                  {% endif%}
              </p>
            </div>
          </div>
        <div class="container all-books my-5">
            <div class="row">
                {% for book in books %}
                <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                    <div class="book my-3 mx-auto">
                        <div class="container">
                            <form action="{% url 'wish' slug=book.slug %}" method="POST">
                                {% csrf_token %}
                                <button class="like-book btn ms-5 book-like" id="like_{{ book.slug }}"><i class="fa-regular fa-heart"></i></button>
                                <input type="hidden" name="redirect_url" value="{{ request.path }}">
                            </form>
                            <a href="{% url 'books:book-details' slug=book.slug %}">
                                <div class="container book-card py-4 px-3">
                                    {% if book.image %}
                                    <img src="{{ book.image.url }}" alt="book image" width="200" height="280">
                                    {% else %}
                                    <a href="{% url 'books:book-details' slug=book.slug %}">
                                        <img class="img-fluid" 
                                            src="{{ MEDIA_URL }}no-image-man.jpg" 
                                            width="200" height="280" alt="no image available">
                                    </a>
                                    {% endif %}
                                    {% if book.special.first %}
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="book-tag">
                                                <div class="special mx-auto">
                                                {{ book.special.first }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endif %}
                                </div>
                            </a>
                        </div>
                        <div class="container">
                           <div class="cotainer book-info">
                                <a class="text-decoration-none" href="{% url 'books:book-details' slug=book.slug %}#about-author">
                                    <small class="author-link">{{ book.author }}</small>
                                </a>
                                <a class="text-decoration-none" href="{% url 'books:book-details' slug=book.slug %}">
                                    <p class="title-link"><strong>{{ book.title }}</strong></p>
                                </a>
                                <div>
                                    <p><strong>{{ book.price }}€</strong></p>
                                </div>
                                {% if book.genre %}
                                <div>
                                    <a class="text-decoration-none" href="#">
                                        <small class="mute genre-link"><i class="fa-solid fa-tag"></i> {{ book.genre }}</small>
                                    </a>
                                </div>
                                {% endif %}
                                {% if book.rating %}
                                <div>
                                    <small class="mute"><i class="fa-solid fa-star"></i> {{ book.rating }} / 5</small>
                                </div>
                                {% else %}
                                    <small> No Rating </small>
                                {% endif %}
                                {% if request.user.is_superuser%}
                                <div class="d-flex justify-content-end">
                                    <a href="{% url 'books:edit_book' slug=book.slug %}" class="text-primary text-decoration-none">edit</a><span class="text-muted">|</span>
                                    <a class="text-danger text-decoration-none" href="{% url 'books:delete_book' slug=book.slug %}" role="button">delete</a>
                                </div>
                                {% endif %}
                           </div>
                        </div>
                    </div>
                </div>
                <!--code idea from code institute WT project:boutique_ado-->
                {% if forloop.counter|divisibleby:1 %}
                <div class="col-12 d-sm-none">
                    <hr class="book-hr">
                </div>
                {% endif %}
                {% if forloop.counter|divisibleby:2 %}
                <div class="col-12 d-none d-sm-block d-md-block d-lg-none">
                    <hr class="book-hr">
                </div>
                {% endif %}
                {% if forloop.counter|divisibleby:3 %}
                <div class="col-12 d-none d-lg-block d-xl-none">
                    <hr class="book-hr">
                </div>
                {% endif %}
                {% if forloop.counter|divisibleby:4 %}
                <div class="col-12 d-none d-xl-block">
                    <hr class="book-hr">
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <!--Books Pagination-->
        {% if is_paginated %}
        <nav aria-label="Page navigation">
            <div class="row">
              <div class="col-12">
                <div class="pagination justify-content-center mb-5">
                  <div class="page-prev">
                    {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}"><i class="fa-solid fa-backward me-1"></i></a>
                    <a href="?page=1" class="page-step-prev">First </a>
                    {% endif %}
                  </div>
                  <div class="ms-2 me-2">
                    <small class="current-page">
                      Page{{ page_obj.number}} of {{ page_obj.paginator.num_pages }}
                    </small>
                  </div>
                  <div class="page-next">
                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.paginator.num_pages }}" class="page-step-next">Last</a>
                    <a href="?page={{ page_obj.next_page_number }}"><i class="fa-solid fa-forward ms-1"></i></a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </nav>
        {% endif %}
    </div>
{% endblock %}

books/templates/books/edit_author.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container page">
    <h2 class="text-center text-uppercase">Author Management</h2>
    <h5 class=" text-center mute">Edit Author</h5>
    <div class="row row-cols-2 my-5">
        <div class="col-12 form mx-auto">
            <form method="POST" action="{% url 'books:edit_author' id=author.id %}"class="text-center my-3" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="d-flex justify-content-center gap-2">
                    <a class="btn btn-secondary" href="{% url 'books:books' %}">Cancel</a>
                    <input type="submit" value="Update Author" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

books/templates/books/edit_book.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container page">
    <h2 class="text-center text-uppercase">Book Management</h2>
    <h5 class=" text-center mute">Edit Book</h5>
    <div class="row row-cols-2 my-5">
        <div class="col-12 form mx-auto">
            <form method="POST" action="{% url 'books:edit_book' slug=book.slug %}"class="text-center my-3" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'image' %}
                        {{ field | as_crispy_field }}
                    {% else %}
                        {{ field }}
                    {% endif %}
                {% endfor %}
                <div class="d-flex justify-content-center gap-2">
                    <a class="btn btn-secondary" href="{% url 'books:books' %}">Cancel</a>
                    <input type="submit" value="Update Book" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}